<?php
    $CONFIG=array("root_path"=>"/biblio_groupe9_etape5/bibliotheque/",
    "dbname"=>"bibliotheque",
    "dbuser"=>"root",
    "dbpwd"=>"",
    "dbhost"=>"localhost",
    "dbport"=>"3306",
    ); 
    ?>